version: '3.8'

volumes:
  postgres_data:

services:
  db:
    image: postgres:12.4
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env
  web:
    build: .
    restart: always
    ports:
      - '8000:8000'
    depends_on:
      - db
    env_file:
      - ./.env
  version: '3.7'
  volumes:
    postgres_data:
    static_volume:
  services:
    db:
      image: postgres:13.1-alpine
      container_name: postgres
      volumes:
        - postgres_data:/var/lib/postgresql/data/
      env_file:
        - ./.env
      restart: always
      networks:
        - db_network
    web:
      image: helenspring/yamdb:latest
      restart: always
      expose:
        - 8000
      command: bash -c "python manage.py collectstatic --noinput && python manage.py migrate && gunicorn api_yamdb.wsgi:application --bind 0.0.0.0:8000"
      volumes:
        - .:/code
        - static_volume:/code/static/
      depends_on:
        - db
      env_file:
        - ./.env
      networks:
        - nginx_network
        - db_network
    nginx:
      image: nginx:1.19.5-alpine
      container_name: nginx
      volumes:
        - static_volume:/code/static/
        - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      ports:
        - "80:80"
      env_file:
        - ./.env
      depends_on:
        - web
